addDrink/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "addDrink"

urlpatterns = [
    path('', views.add_drink, name="add_drink"),
    path('allDrinks/getAllDrinks/', views.get_all_drinks, name="get_drink"),
    path('allDrinks/', views.show_all_drinks, name="all_drink")
]

login/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include,path
from . import views

app_name = "login"

urlpatterns = [
	path('', views.loginuser, name='loginpage'),
]

tugasKelompokPPW/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('findDrinks.urls')),    
    path('register/', include('register.urls')),
    path('addDrink/', include('addDrink.urls')),
    path('', include('login.urls'))
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

addDrink/models.py
from django.db import models


class Minuman(models.Model):
    CATEGORY_CHOICES =(
        ('milk','Milk'),
        ('tea','Tea'),
        ('coffee','Coffee'),
        ('softdrinks','Soft Drinks'),
        ('others','Others')
    )
    FLAVORS = (
        ('none','None'),
        ('chocolate','Chocolate'),
        ('vanilla','Vanilla'),
        ('fruit','Fruit')
    )
    SUGAR_RATES = (
        ('zero','0%'),
        ('quarter','25%'),
        ('half','50%'),
        ('threeQuarter','75%'),
        ('full','100%')
    )
    HOT_OR_ICE = (
        ('hot','Hot'),
        ('ice','Ice'),
    )
    BLEND_OR_BREW = (
        ('blend','Blend'),
        ('brew','BREW')
    )

    drink_name = models.CharField(max_length= 75)
    category = models.CharField(max_length= 20, choices=CATEGORY_CHOICES)
    flavor = models.CharField(max_length = 20, choices = FLAVORS)
    sugar_rate = models.CharField(max_length=20, choices = SUGAR_RATES)
    hot_or_ice = models.CharField(max_length = 20, choices = HOT_OR_ICE)
    blend_or_brew = models.CharField(max_length=20, choices= BLEND_OR_BREW)
    store_name = models.CharField(max_length=75)
    store_location = models.CharField(max_length=75)
    price = models.IntegerField()
    drink_image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.drink_name

addDrink/forms.py
from .models import Minuman
from django import forms

class FormAddDrink(forms.ModelForm):
    drink_name = forms.CharField(
        widget = forms.TextInput(
            attrs= {
                "class":"txt-form",
                "required": True,
                "placeholder": "Enter the name of the drink",
            }
        )
    )
    category = forms.CharField(
        widget= forms.Select(
            attrs={
                "class" : "dropdown-item",
            },
            choices = Minuman.CATEGORY_CHOICES, 
        )
    )
    flavor = forms.CharField(
        widget = forms.Select(
            attrs={
                "class": "dropdown-item",
            },
            choices = Minuman.FLAVORS,
        )
    )
    sugar_rate = forms.CharField(
        widget = forms.Select(
            attrs= {
                "class":"dropdown-item",
            },
            choices=Minuman.SUGAR_RATES,
        )
    )
    hot_or_ice = forms.CharField(
        widget = forms.Select(
            attrs = {
                "class":'dropdown-item',
            },
            choices = Minuman.HOT_OR_ICE,
        )
    )
    blend_or_brew = forms.CharField(
        widget = forms.Select(
            attrs={
                "class":'dropdown-item',
            },
            choices= Minuman.BLEND_OR_BREW,
        )
    )
    store_name = forms.CharField(
        widget = forms.TextInput(
            attrs ={
                "class":'txt-form',
                "placeholder" : "Enter name of the store",
            }
        )
    )
    store_location = forms.CharField(
        widget = forms.TextInput(
            attrs ={
                "class":'txt-form',
                "placeholder" : "Enter location of the store",
            }
        )
    )
    price = forms.IntegerField(
        widget = forms.NumberInput(
            attrs = {
                "class": 'txt-form',
                "placeholder" : "Enter the price for of the drink",
            }
        )
    )
    drink_image = forms.ImageField(
        widget = forms.FileInput(
            attrs = {
                "id": '',
            }
        )
    )

    class Meta:
        model = Minuman
        fields= [
            'drink_name', 'category', 'flavor', 'sugar_rate', 'hot_or_ice', 'blend_or_brew',
            'store_name', 'store_location', 'price', 'drink_image',
        ]

addDrink/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http.response import JsonResponse
from django.contrib.auth.decorators import login_required
from django.core import serializers
from . import models
from . import forms

""" Function for outputing add drink form """
@login_required(login_url='/')
def add_drink(request):
    form = forms.FormAddDrink()
    if request.method == "POST":
        form = forms.FormAddDrink(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('addDrink:add_drink')
    return render(request, 'addDrink/add_drink.html', {'form':form})

"""Function for send all drink data in JSON format"""
@login_required(login_url='/')
def get_all_drinks(request):
    all_drinks = models.Minuman.objects.all()
    return HttpResponse(serializers.serialize('json', all_drinks), 
        content_type= "text/json-comment-filtered")

"""Function for render template all drinks"""
@login_required(login_url='/')
def show_all_drinks(request):
    return render(request, 'addDrink/list_drink.html')

addDrink/templates/addDrink/add_drink.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" >
    <link rel="stylesheet" href="{% static 'css/style-christo.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <title>Add Drink</title>
</head>
<nav class="navbar navbar-expand-lg navbar-light fixed-top bg-cream-muda" id="navigation">
    <div id="left-nav">
        <a class="navbar-brand" href="#" id="logo">
            <img src="{% static 'img/logo-kecil.png' %}" alt="" id="logo">
        </a>
    </div>

    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon" id="tombol-nav"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <div class="navbar-nav ml-auto">
            <a class="nav-link nav-item" href="{% url 'addDrink:add_drink' %}">Add Drink<span class="sr-only">(current)</span></a>
            <a class="nav-link nav-item" href="{% url 'addDrink:all_drink' %}">List Drinks<span class="sr-only">(current)</span></a>
            <a class="nav-link nav-item" href="#">Feedback</a>
            <a class="nav-link nav-item" href="/logout/">Logout</a>
        </div>
    </div>
</nav>

<body class="bg-cream-muda">
    <div class="flex-container column-style" id="add-drink">
        <div class="flex-container column-style bg-cream" id="addDrink-form">
            <span class="title">Add Drinks</span>
            <form action="" method="POST" class="isian-form" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="flex-container column-style isian-form">
                    <span class="subtitle">Name of the drink</span>
                    {{ form.drink_name }}
                    <span class="subtitle">Category</span>
                    {{ form.category }}
                    <span class="subtitle">Flavor</span>
                    {{ form.flavor }}
                    <span class="subtitle">Sugar Rate</span>
                    {{ form.sugar_rate }}
                    <span class="subtitle">Hot or Ice</span>
                    {{ form.hot_or_ice }}
                    <span class="subtitle">Blend or Brew</span>
                    {{ form.blend_or_brew }}
                    <span class="subtitle">Store Name</span>
                    {{ form.store_name }}
                    <span class="subtitle">Store Location</span>
                    {{ form.store_location }}
                    <span class="subtitle">Price</span>
                    {{ form.price }}
                    <span class="subtitle">Picture</span>
                    {{ form.drink_image }}
                    <div class="flex-container row-style" id="add-btn">
                        <input type="submit" class="tombol" value="Add" />
                    </div>
                </div>
            </form>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.js"
        integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>
<footer>
    <h3>Est. 2019 by FindDrinks</h3>
</footer>
</html>

addDrink/templates/addDrink/list_drink.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" >
    <link rel="stylesheet" href="{% static 'css/style-christo.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.4.1.js"
        integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
        crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/scriptChristo.js' %}"></script>
    <title>List Drinks</title>
</head>
<nav class="navbar navbar-expand-lg navbar-light fixed-top bg-cream-muda" id="navigation">
    <div id="left-nav">
        <a class="navbar-brand" href="#" id="logo">
            <img src="{% static 'img/logo-kecil.png' %}" alt="" id="logo">
        </a>
    </div>

    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon" id="tombol-nav"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <div class="navbar-nav ml-auto">
            <a class="nav-link nav-item" href="{% url 'addDrink:add_drink' %}">Add Drink<span class="sr-only">(current)</span></a>
            <a class="nav-link nav-item" href="{% url 'addDrink:all_drink' %}">List Drinks<span class="sr-only">(current)</span></a>
            <a class="nav-link nav-item" href="#">Feedback</a>
            <a class="nav-link nav-item" href="/logout/">Logout</a>
        </div>
    </div>
</nav>
<body class="bg-cream-muda">
    <div class="flex-container column-style" id="list-drink">
        <span class="title">List All Drinks</span>
        <div class="flex-container" id="all-drinks">

        </div>
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>
</html>