login/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include,path
from . import views

app_name = "login"

urlpatterns = [
	path('', views.loginuser, name='loginpage'),
]

register/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "register"

urlpatterns = [
    path('', views.register, name='register'),
    path('ajax/check_username/', views.check_username, name='check_username')
]

tugasKelompokPPW/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('findDrinks.urls')),    
    path('register/', include('register.urls')),
    path('addDrink/', include('addDrink.urls')),
    path('', include('login.urls'))
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/forms.py
from django import forms
from .models import Login

class LoginForm(forms.ModelForm):
	username=forms.CharField(
		widget=forms.TextInput(
			attrs={
				'required':True,
			}
		)
	)
	password = forms.CharField(
		widget= forms.PasswordInput(
			attrs = {
				'required' :True,
			}
		)
	)
	class Meta:
		model = Login
		fields = ('username', 'password')

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login

# Create your views here.
def loginuser(request):
	if request.user.is_superuser and request.user.is_authenticated:
		return redirect('/addDrink/')
	if request.user.is_authenticated:
		return redirect('/findDrinks/')
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			user = form.get_user()
			login(request, user)
			if request.user.is_superuser:
				return redirect('/addDrink/')
			else:
				return redirect('/findDrinks/')
	else:
		form = AuthenticationForm()
	return render(request, 'login.html', {'form':form})

login/templates/login.html
{% extends 'navbar.html' %}
{% load static %}



{% block title %}
    <title>Login</title>
    <link rel="stylesheet" type="text/css"  href="{% static 'css/styleRifqi.css' %}">
{% endblock %}

{% block content %}
<body>
    <div class="flex-container">
        <form method="POST" class="register_form">
            {% csrf_token %}
                <h4 id="upper">Login to continue</h4>
                {{ form.as_p }}
                <button type="submit" class="btn button-register">Login</button>
                <h6 id="lower">Don't have an account? <a href="{% url 'register:register' %}">Create one now</a> </h6>
        </form>
    </div>  
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="{% static 'js/bootstrap.js' %}"></script>
</body>

{% endblock %}