findDrinks/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include,path
from findDrinks import views

app_name = "findDrinks"

urlpatterns = [
    path('findDrinks/', views.findDrinks, name='findDrinks'),
    path('logout/', views.logout, name='logout'),
    path('getRecommendation/<slug:category>/', views.getRecommendation, name='getRecommendation'),
]

login/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include,path
from . import views

app_name = "login"

urlpatterns = [
	path('', views.loginuser, name='loginpage'),
]

tugasKelompokPPW/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('findDrinks.urls')),    
    path('register/', include('register.urls')),
    path('addDrink/', include('addDrink.urls')),
    path('', include('login.urls'))
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/navbar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" >
    <link rel="stylesheet" href="{% static 'css/style-christo.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    {% block title %}

    {% endblock %}
</head>
<nav class="navbar navbar-expand-lg navbar-light fixed-top bg-cream-muda" id="navigation">
    <div id="left-nav">
        <a class="navbar-brand" href="#" id="logo">
            <img src="{% static 'img/logo-kecil.png' %}" alt="" id="logo">
        </a>
    </div>

    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon" id="tombol-nav"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <div class="navbar-nav ml-auto">
            <a class="nav-link nav-item" href="{% url 'findDrinks:findDrinks' %}">Find Drink<span class="sr-only">(current)</span></a>
            <a class="nav-link nav-item" href="#">Feedback</a>
            {% if user.is_authenticated %}
            <a class="nav-link nav-item" href="/logout/">Logout</a>
            {% else %}
            <a class="nav-link nav-item" href="{% url 'login:loginpage' %}">Login</a>
            {% endif %}
        </div>
    </div>
</nav>
{% block content %}


{% endblock %}

<footer>
    <h3>Est. 2019 by FindDrinks</h3>
</footer>
</html>